### ISSUE TITLE
Questions about ground truth format.

### ISSUE THREAD

**Issue by iHateTa11B0y** [javiribera/locating-objects-without-bboxes#10]
Hi,

I was reading the help information of command `python3.6 -m object-locator.locate -h` offered me when I came across 

> --dataset DATASET  &#160;&#160; Directory with test images. Must contain image files 
&#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; (any format), and CSV or XML file containing a
&#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160;groundtruth file following the API v0.4 (default:
&#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160; &#160;&#160;None)

As far as I know, the groudtruth in mall dataset is a `.mat` file which is  unable to use directly.
I have no clue about what '**API v0.4**' refers to. Is there any documents that I can catch up with? 

Thanks.

**Comment by javiribera** [comment]
It is understandable this brings confusion since that part of the documentation is not publicly available. I added some clarifications in the readme file and in the docstrings (via commit 878e43fc09e087ed45ccf05fbb67195b0f38be62).

In summary: unless you know you need to use an XML file, whose specifications we designed for a precision agriculture application, you should always use a CSV. Ignore all mentions to XMLs.

Thanks,

**Comment by iHateTa11B0y** [comment]
That definitely make more sense to me. Thanks for your quick reply btw ^^
