### ISSUE TITLE
Extend WeightedHausdorffDistance to 3D Images

### ISSUE THREAD

**Issue by sunformoon** [javiribera/locating-objects-without-bboxes#4]

**Comment by sunformoon** [comment]
Great work! I would like to apply the WeightedHausdorffDistance on 3D images.
I checked the [loss function](https://github.com/javiribera/locating-objects-without-bboxes/blob/master/object-locator/losses.py). The current loss only applies to 2D images. Would it be pretty straightforward to modify the loss to calculate the distance in 3D scenario?

Any comments on it would be great appreciate.

**Comment by javiribera** [comment]
I think it should be pretty straightforward to generalized the WeightedHausdorffDistance to 3D or more dimensions. In the original derivation in the paper, Omega can be set to R^3 and everything else remains the same. In the code of [WeightedHausdorffDistance](https://github.com/javiribera/locating-objects-without-bboxes/blob/master/object-locator/losses.py#L120), one would need to replace resized_height and resized_width with a tuple with 2 or more elements, precompute the cartesian coordinates accordingly [here](https://github.com/javiribera/locating-objects-without-bboxes/blob/master/object-locator/losses.py#L145), and some other minor changes.

The memory requirements may blow up quickly, though, since we pre-compute all the possible cartesian coordinates, and compute d(x, y) between all coordinates and each point in the ground truth Y. The current implementation does this in parallel [here](https://github.com/javiribera/locating-objects-without-bboxes/blob/master/object-locator/losses.py#L210) to emphasize speed over memory requirements. If one expects few groundtruth points, I would first extend this implementation to 3D, since it seems like a low hanging fruit.

I'd be happy to accept a pull request about this.
